name: WakaTime README Generator

on:
  schedule:
    - cron: '30 18 * * *'  # 17:00 UTC+00
  workflow_dispatch:
jobs:
  update-readme:
    name: Update README.md with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
